version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dating_web
    expose:
      - "5000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: dating_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./app/static:/var/www/app/static:ro
    depends_on:
      - web
    restart: unless-stopped
