version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dating_web
    expose:
      - "5000"
    volumes:
      - ./app:/app
      - ./data:/app/data
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: dating_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: unless-stopped
  # certbot:
  #   image: certbot/certbot
  #   container_name: dating_certbot
  #   volumes:
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/conf:/etc/letsencrypt
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
  #   restart: unless-stopped
