version: '3'

services:
  flask:
    build: ./app
    ports:
      - "5000:5000"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8443:8443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #   depends_on:
  #     - flask
