services:
  flask:
    build: ./app
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: dating_nginx_test
    ports:
      - "80:80"
      - "8443:8443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flask
    restart: always
